name: Buildx Pull Ubuntu and Push to Aliyun ACR

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. checkout 代码（虽然本例不依赖代码，也必须执行）
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 QEMU（支持 arm64）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3. 设置 buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 登录到阿里云容器镜像服务
      - name: Login Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      # 5. 构建并推送到阿里云
      - name: Buildx build and push to ACR
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --no-cache \
            -f Dockerfile \
            -t ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/ubuntu:22.04 \
            --push \
            .
